version: "3"

services:
  bank-core:
    container_name: bank-core
    image: golang:1.19
    command: go run cmd/bank-server/main.go
    working_dir: /app
    volumes:
      - "../../:/app"
    ports:
      - "8080:8080"